services:
  devops-be:
    build: ./tp-devops-be
    ports:
      - "3001:3001"
    hostname: "devops_be"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=devops_db
      - DB_PORT=5432
      - DB_USER=devuser
      - DB_PASS=devpass
      - DB_NAME=devops
    depends_on:
      devops_db:
        condition: service_healthy
  devops_fe:
    build: ./tp-devops-fe
    ports:
      - "3000:3000"
    volumes:
      - ./tp-devops-fe/src:/app/src
      - ./tp-devops-fe/public:/app/public
      - ./tp-devops-fe/package.json:/app/package.json
      - ./tp-devops-fe/tsconfig.json:/app/tsconfig.json
    depends_on:
      - devops-be
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_PUBLIC_BE_SCHEMA=http
      - NEXT_PUBLIC_BE_HOST=devops_be
      - NEXT_PUBLIC_BE_PORT=3001
  devops_db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=devops
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    ports:
      - "5432:5432"
    volumes:
      - devops_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d devops"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  devops_db_data:
