app = "tp-devops-db"
primary_region = "mia"

[env]
  POSTGRES_DB = "devops"
  POSTGRES_USER = "devuser"

[[services]]
  internal_port = 5432
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "connections"

  [[services.ports]]
    handlers = ["pg_tls"]
    port = 5432

  [services.tcp_checks]
    interval = "15s"
    grace_period = "1s"
    restart_limit = 0
    timeout = "2s"

[processes]
  app = "postgres"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# PostgreSQL específico
[mounts]
  source = "devops_data"
  destination = "/var/lib/postgresql/data"