apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-be
  template:
    metadata:
      labels:
        app: devops-be
    spec:
      containers:
      - name: devops-be
        image: ramirezcgn/tp-devops-be:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: devops-db
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: devuser
        - name: DB_PASS
          value: devpass
        - name: DB_NAME
          value: devops
        - name: REDIS_HOST
          value: devops-redis
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-be
spec:
  selector:
    app: devops-be
  ports:
  - port: 8080
    targetPort: 8080
