name: Deploy FE & BE to Render
on:
  push:
    branches:
      - main
jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy FE to Render
        uses: JorgeLNJunior/render-deploy@v1.4
        with:
          service_id: ${{ secrets.RENDER_FE_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BE to Render
        uses: JorgeLNJunior/render-deploy@v1.4
        with:
          service_id: ${{ secrets.RENDER_BE_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
