name: Deploy to Render
on:
  push:
    branches:
      - develop
jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy FE to Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_FE_DEV_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_DEV_API_KEY }}
          wait_deploy: true
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BE to Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_BE_DEV_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_DEV_API_KEY }}
          wait_deploy: true
